package viewGUI.app.res;

import java.util.ListResourceBundle;

public class Bundle_by_BY extends ListResourceBundle {
    @Override
    protected Object[][] getContents() {
        return new Object[][]{
                {"authorization", "Аўтарызацыя"},
                {"app", "Прыкладанне"},
                {"editUtility", "Edit Utility"},
                {"addUtility", "Утыліта рэдагавання"},
                {"enterPoint", "Экран ўваходу"},
                {"myName", "Кірыл Лалаянц"},
                {"userNameField", "Увайсці"},
                {"passwordField", "Пароль"},
                {"loginButton", "Увайсці"},
                {"registerButton", "Зарэгіструйцеся"},
                {"dataTab", "Дадзеныя"},
                {"mapTab", "Карта"},
                {"idColumn", "id"},
                {"nameColumn", "Імя"},
                {"dateColumn", "Дата"},
                {"xColumn", "x"},
                {"yColumn", "y"},
                {"minPointColumn", "Мінімальная кропка"},
                {"personalPointColumn", "Асабістая кропка"},
                {"difficultyColumn", "Цяжкасць"},
                {"authorColumn", "Аўтар"},
                {"weightColumn", "Вага"},
                {"colorColumn", "Афарбоўка"},
                {"creatorsIdColumn", "Ідэнтыфікатар стваральніка"},
                {"labWorkDetails", "Падрабязнасці LabWork"},
                {"idDetails", "id"},
                {"nameDetails", "Імя"},
                {"xDetails", "x"},
                {"yDetails", "y"},
                {"dateDetails", "Дата"},
                {"minimalPointDetails", "Мінімальная кропка"},
                {"personalPointDetails", "Асабістая кропка"},
                {"difficultyDetails", "Цяжкасць"},
                {"authorDetails", "Аўтар"},
                {"weightDetails", "Вага"},
                {"eyeColorDetails", "Афарбоўка"},
                {"editButton", "Рэдагаваць"},
                {"addButton", "Дадаць"},
                {"removeButton", "Выдаліць"},
                {"clearButton", "Чысціць"},
                {"cancelButton", "Адмяніць"},
                {"success", "Поспех"},
                {"successOfEdit", "LabWork адрэдагаваны"},
                {"successOfEditMessage", "LabWork паспяхова адрэдагаваны"},
                {"LabWorkEditError", "Памылка рэдагавання LabWork"},
                {"LabWorkEditErrorNotSpecified", "Выберыце, што рэдагаваць у першую чаргу"},
                {"LabWorkEditErrorNotYours", "Вы не можаце рэдагаваць іншыя LabWorks"},
                {"LabWorkFillError", "Памылка запаўнення"},
                {"labWorkRemove", "Выдаленне LabWork"},
                {"labWorkRemoveSuccess", "LabWork паспяхова выдалены"},
                {"error", "Памылка"},
                {"labWorkRemoveError", "Вы не можаце выдаліць іншыя LabWorks"},
                {"labWorkRemoveErrorNotSpecified", "Выберыце, што выдаліць у першую чаргу"},
                {"confirmation", "Пацвярджэнне"},
                {"confirmationOfClear", "Пацвярджэнне ясна"},
                {"confirmationOfClearMessage", "Вы сапраўды хочаце выдаліць усе свае LabWorks?"},
                {"nameFillError", "Імя трэба ўвесці\n"},
                {"authorFillError", "Аўтар павінен быць уведзены\n"},
                {"difficultyFillError", "Трэба ўвесці складанасць\n"},
                {"eyeColorFillError", "Трэба ўвесці колер вачэй\n"},
                {"xFillError", "Х павінен быць лікам\n"},
                {"yFillError", "Y павінна быць цэлым лікам\n"},
                {"weightFillError", "Вага павінна быць лічбай\n"},
                {"personalPointFillError", "Асабістая кропка павінна быць цэлым лікам\n"},
                {"minimalPointFillError", "Мінімальная кропка павінна быць лічбай\n"},
                {"Имя пользователя занято", "Імя карыстальніка ўжо выкарыстоўваецца"},
                {"loginErrorEmptyField", "Абодва палі павінны быць уведзены"},
                {"Неверный логин или пароль", "Няправільны лагін або пароль"},

                {"commandTab", "Іншыя каманды"},
                {"removeLower", "Зніміце ніжні"},
                {"addIfMin", "Дадаць, калі мін"},
                {"removeLowerAnswerNoElements", "Няма элементаў ніжэй за ўведзеныя"},
                {"removeLowerAnswerSuccess", "Элементы выдаляюцца"},
                {"AddIfMinAnswerNotMin", "Уведзены элемент не мінімальны"},
                {"AddSuccess", "Элемент паспяхова дададзены"},
                {"uniqueMinimalPointButton", "Унікальная мінімальная кропка"},
                {"countLessThanMinimalPointButton", "Лічыце менш за мінімальны бал"},
                {"getUniqueMinimalPointAnswerEmpty", "Калекцыя пустая"},
                {"", ""},
        };
    }
}
