package viewGUI.app.res;

import java.util.ListResourceBundle;

public class Bundle_ru_RU extends ListResourceBundle {
    @Override
    protected Object[][] getContents() {
        return new Object[][] {
                {"authorization", "Авторизация"},
                {"app", "Приложение"},
                {"editUtility", "Редактирование"},
                {"addUtility", "Добавление"},
                {"enterPoint", "Вход в приложение"},
                {"myName", "Кирилл Лалаянц"},
                {"userNameField", "Логин"},
                {"passwordField", "Пароль"},
                {"loginButton", "Вход"},
                {"registerButton", "Регистрация"},
                {"dataTab", "Данные"},
                {"mapTab", "Карта"},
                {"idColumn", "id"},
                {"nameColumn", "Имя"},
                {"dateColumn", "Дата"},
                {"xColumn", "x"},
                {"yColumn", "y"},
                {"minPointColumn", "Минимальный балл"},
                {"personalPointColumn", "Личный балл"},
                {"difficultyColumn", "Сложность"},
                {"authorColumn", "Автор"},
                {"weightColumn", "Вес"},
                {"colorColumn", "Цвет"},
                {"creatorsIdColumn", "id Создателя"},
                {"labWorkDetails", "Детали работы"},
                {"idDetails", "id"},
                {"nameDetails", "Имя"},
                {"xDetails", "x"},
                {"yDetails", "y"},
                {"dateDetails", "Дата"},
                {"minimalPointDetails", "Минимальный балл"},
                {"personalPointDetails", "Личный балл"},
                {"difficultyDetails", "Сложность"},
                {"authorDetails", "Автор"},
                {"weightDetails", "Вес"},
                {"eyeColorDetails", "Цвет"},
                {"editButton", "Изменить"},
                {"addButton", "Добавить"},
                {"removeButton", "Удалить"},
                {"clearButton", "Удалите все"},
                {"cancelButton", "Отмена"},
                {"success", "Успех"},
                {"successOfEdit", "Редактирование работы"},
                {"successOfEditMessage", "Отредактировано успешно"},
                {"LabWorkEditError", "Ошибка редактирования работы"},
                {"LabWorkEditErrorNotSpecified", "Выберите, какую работу редактировать"},
                {"LabWorkEditErrorNotYours", "Вы не можете редактировать чужие работы"},
                {"LabWorkFillError", "Ошибка заполнения"},
                {"labWorkRemove", "Удаление работы"},
                {"labWorkRemoveSuccess", "Работы успешно удалена"},
                {"error", "Ошибка"},
                {"labWorkRemoveError", "Вы не можете удалять чужие работы"},
                {"labWorkRemoveErrorNotSpecified", "Выберите, какую работу удалить"},
                {"confirmation", "Подтверждение"},
                {"confirmationOfClear", "Подтверждение удаления"},
                {"confirmationOfClearMessage", "Вы уверены, что хотите удалить все свои работы?"},
                {"nameFillError", "Имя должно быть введено\n"},
                {"difficultyFillError", "Сложность должна быть введена\n"},
                {"eyeColorFillError", "Цвет должен быть введен\n"},
                {"authorFillError", "Автор должен быть введен\n"},
                {"xFillError", "X должен быть десятичной дробью\n"},
                {"yFillError", "Y должен быть целым числом\n"},
                {"weightFillError", "Вес должен быть десятичной дробью\n"},
                {"personalPointFillError", "Личный балл должен быть целым числом\n"},
                {"minimalPointFillError", "Минимальный балл должен быть десятичной дробью\n"},
                {"Имя пользователя занято", "Имя пользователя занято"},
                {"loginErrorEmptyField", "Оба поля должны быть заполнены"},
                {"Неверный логин или пароль", "Неверный логин или пароль"},
                {"commandTab", "Other commands"},
                {"removeLower", "Убрать наименьший"},
                {"addIfMin", "Добавить, если мин"},
                {"removeLowerAnswerNoElements", "Нет элемента меньше заданного"},
                {"removeLowerAnswerSuccess", "Элементы удалены"},
                {"AddIfMinAnswerNotMin", "Введенная не минимальная"},
                {"AddSuccess", "Элемент успешно добавлен"},
                {"uniqueMinimalPointButton", "Уникальные мин баллы"},
                {"countLessThanMinimalPointButton", "Меньше, чем заданный мин балл"},
                {"getUniqueMinimalPointAnswerEmpty", "Коллекция пуста"},
                {"", ""},


        };
    }
}