package viewGUI.app.res;

import java.util.ListResourceBundle;

public class Bundle_se_SE extends ListResourceBundle {
    @Override
    protected Object[][] getContents() {
        return new Object[][] {
                {"authorization", "Tillstånd"},
                {"app", "App"},
                {"editUtility", "Redigera verktyg"},
                {"addUtility", "Lägg till verktyg"},
                {"enterPoint", "Inloggningsskärm"},
                {"myName", "Kirill Lalayants"},
                {"userNameField", "Logga in"},
                {"passwordField", "Lösenord"},
                {"loginButton", "Logga in"},
                {"registerButton", "Registrera"},
                {"dataTab", "Data"},
                {"mapTab", "Karta"},
                {"idColumn", "id"},
                {"nameColumn", "Namn"},
                {"dateColumn", "Datum"},
                {"xColumn", "x"},
                {"yColumn", "y"},
                {"minPointColumn", "Minimal poäng"},
                {"personalPointColumn", "Personlig poäng"},
                {"difficultyColumn", "Svårighet"},
                {"authorColumn", "Författare"},
                {"weightColumn", "Vikt"},
                {"colorColumn", "Färg"},
                {"creatorsIdColumn", "Skaparens id"},
                {"labWorkDetails", "LabWork detaljer"},
                {"idDetails", "id"},
                {"nameDetails", "Namn"},
                {"xDetails", "x"},
                {"yDetails", "y"},
                {"dateDetails", "Datum"},
                {"minimalPointDetails", "Minimal poäng"},
                {"personalPointDetails", "Personlig poäng"},
                {"difficultyDetails", "Svårighet"},
                {"authorDetails", "Författare"},
                {"weightDetails", "Vikt"},
                {"eyeColorDetails", "Färg"},
                {"editButton", "Redigera"},
                {"addButton", "Lägg till"},
                {"removeButton", "Ta bort"},
                {"clearButton", "Klar"},
                {"cancelButton", "Avbryt"},
                {"success", "Framgång"},
                {"successOfEdit", "LabWork redigerade"},
                {"successOfEditMessage", "LabWork har redigerats"},
                {"LabWorkEditError", "LabWork redigeringsfel"},
                {"LabWorkEditErrorNotSpecified", "Välj vad som ska redigeras först"},
                {"LabWorkEditErrorNotYours", "Du kan inte redigera andra LabWorks"},
                {"LabWorkFillError", "Fyllningsfel"},
                {"labWorkRemove", "Borttagning av LabWork"},
                {"labWorkRemoveSuccess", "LabWork har tagits bort"},
                {"error", "Fel"},
                {"labWorkRemoveError", "Du kan inte ta bort andra LabWorks"},
                {"labWorkRemoveErrorNotSpecified", "Välj vad som ska raderas först"},
                {"confirmation", "Bekräftelse"},
                {"confirmationOfClear", "Bekräftelse av klar"},
                {"confirmationOfClearMessage", "Vill du verkligen ta bort alla dina LabWorks?"},
                {"nameFillError", "Namn måste anges\n"},
                {"authorFillError", "Författare måste anges\n"},
                {"difficultyFillError", "Svårighetsgrad måste anges\n"},
                {"eyeColorFillError", "Ögonfärg måste anges\n"},
                {"xFillError", "X måste vara ett tal\n"},
                {"yFillError", "Y måste vara ett heltal\n"},
                {"weightFillError", "Vikten måste vara en siffra\n"},
                {"personalPointFillError", "Personlig poäng måste vara ett heltal\n"},
                {"minimalPointFillError", "Minsta poäng måste vara en siffra\n"},
                {"Имя пользователя занято", "Användarnamnet används redan"},
                {"loginErrorEmptyField", "Båda fälten måste anges"},
                {"Неверный логин или пароль", "Fel inloggning eller lösenord"},
                {"commandTab", "Andra kommandon"},
                {"removeLower", "Ta bort nedre"},
                {"addIfMin", "Tillsätt om min"},
                {"removeLowerAnswerNoElements", "Det finns inga element lägre än angivna"},
                {"removeLowerAnswerSuccess", "Element tas bort"},
                {"AddIfMinAnswerNotMin", "Inmatat element är inte minimalt"},
                {"AddSuccess", "Elementet har lagts till"},
                {"uniqueMinimalPointButton", "Unik minpunkt"},
                {"countLessThanMinimalPointButton", "Räkna mindre än minimal poäng"},
                {"getUniqueMinimalPointAnswerEmpty", "Samlingen är tom"},
                {"", ""},
        };
    }
}
