package viewGUI.app.res;

import java.util.ListResourceBundle;

public class Bundle_en_AU extends ListResourceBundle {
    @Override
    protected Object[][] getContents() {
        return new Object[][] {
                {"authorization", "Authorization"},
                {"app", "App"},
                {"editUtility", "Edit Utility"},
                {"addUtility", "Add Utility"},
                {"enterPoint", "Login screen"},
                {"myName", "Kirill Lalayants"},
                {"userNameField", "Login"},
                {"passwordField", "Password"},
                {"loginButton", "Login"},
                {"registerButton", "Register"},
                {"dataTab", "Data"},
                {"mapTab", "Map"},
                {"idColumn", "id"},
                {"nameColumn", "Name"},
                {"dateColumn", "Date"},
                {"xColumn", "x"},
                {"yColumn", "y"},
                {"minPointColumn", "Minimal point"},
                {"personalPointColumn", "Personal point"},
                {"difficultyColumn", "Difficulty"},
                {"authorColumn", "Author"},
                {"weightColumn", "Weight"},
                {"colorColumn", "Color"},
                {"creatorsIdColumn", "Creator's id"},
                {"labWorkDetails", "LabWork details"},
                {"idDetails", "id"},
                {"nameDetails", "Name"},
                {"xDetails", "x"},
                {"yDetails", "y"},
                {"dateDetails", "Date"},
                {"minimalPointDetails", "Minimal point"},
                {"personalPointDetails", "Personal point"},
                {"difficultyDetails", "Difficulty"},
                {"authorDetails", "Author"},
                {"weightDetails", "Weight"},
                {"eyeColorDetails", "Eye Colour"},
                {"editButton", "Edit"},
                {"addButton", "Add"},
                {"removeButton", "Remove"},
                {"clearButton", "Clear"},
                {"cancelButton", "Cancel"},
                {"success", "Success"},
                {"successOfEdit", "LabWork edited"},
                {"successOfEditMessage", "LabWork edited successfully"},
                {"LabWorkEditError", "LabWork edit error"},
                {"LabWorkEditErrorNotSpecified", "Choose what to edit first"},
                {"LabWorkEditErrorNotYours", "You can't edit others LabWorks"},
                {"LabWorkFillError", "Filling error"},
                {"labWorkRemove", "LabWork removal"},
                {"labWorkRemoveSuccess", "LabWork removed successfully"},
                {"error", "Error"},
                {"labWorkRemoveError", "You can't remove others LabWorks"},
                {"labWorkRemoveErrorNotSpecified", "Choose what to delete first"},
                {"confirmation", "Confirmation"},
                {"confirmationOfClear", "Confirmation of clear"},
                {"confirmationOfClearMessage", "Do you really want to delete all your LabWorks?"},
                {"nameFillError", "Name has to be entered\n"},
                {"authorFillError", "Author has to be entered\n"},
                {"difficultyFillError", "Difficulty has to be entered\n"},
                {"eyeColorFillError", "Eye Color has to be entered\n"},
                {"xFillError", "X has to be a number\n"},
                {"yFillError", "Y has to be an integer\n"},
                {"weightFillError", "Weight has to be a number\n"},
                {"personalPointFillError", "Personal point has to be an integer\n"},
                {"minimalPointFillError", "Minimal point has to be a number\n"},
                {"Имя пользователя занято", "Username is already used"},
                {"loginErrorEmptyField", "Both fields must be entered"},
                {"Неверный логин или пароль", "Incorrect login or password"},




        };
    }
}
